# Generated by Django 5.2.4 on 2025-08-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precipitation', models.FloatField(default=0.0)),
                ('max_temp', models.FloatField(default=0.0)),
                ('min_temp', models.FloatField(default=0.0)),
                ('wind_speed', models.FloatField(default=0.0)),
                ('res', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
    ]
